# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19toKptikBpJNPlE0qN-qoIES7cIhgF4v
"""

def kasallik_tashxisi(belgi):
  if belgi == "Istima":
   return "Parasitamol iching"
  elif belgi =="Bosh og'rig'i":
   return "Bolnol"
  elif belgi =="Oyoq og'rig'i":
   return "og'riq qoldiradigon"
  elif belgi =="Tish og'rig'i":
   return "Senepar"
  elif belgi =="tizza og'rig'i":
   return "bolnol"
  elif belgi =="ko'z og'rig'i":
   return "furatsilinli suvda yuv"
  elif belgi =="tirnoq og'rig'i":
   return "tirnoq olish"
  elif belgi =="oshqozon og'rig'i":
   return "kamroq yeyish kere"
  elif belgi =="opka og'rig'i":
   return "chekishni tashla"
  elif belgi =="uyqusizlik":
   return "kamroq tel oyna "
  else:
   return"Shifokorga murojot qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)

def kinolar(turlar):
  if turlari == "fantastik":
   return "DC va Marvel"
  elif turlari =="kamediya":
   return "Uchinchisi ortiqcha 2"
  elif turlari =="#Drama #Melodrama":
   return "Muhabbat masofasi"
  elif turlari =="#Boyevik #Komediya #Triller":
   return "Janob Smit va Smit xonim"
  elif turlari =="#Triller #Drama #Melodrama":
   return " Narkoz"
  elif turlari =="#Komediya #Kriminal":
   return "Pakana odam"
  elif turlari =="#Drama #Biografiya":
   return "Ijtimoiy tarmoq"
  elif turlari =="#Drama #Kriminal #Triller":
   return "Joker"
  elif turlari =="#Triller #Drama #Kriminal":
   return "Jinoyatchi"
  elif turlari =="#Boyevik #Komediya":
   return "Dedpul"
  else:
    return "uzur boshqachasini bilmayman"
turlari=input("kino janrini yoz ")
natija=kinolar(turlari)
print(natija)